- name: Setup
  hosts: staging
  serial: 1
  vars:
    branch: origin/feature/new-deployment

  tasks:
    - name: import secret variable file
      include_vars: "secret_key.yml"

    - name: Ping
      ansible.builtin.ping:

    - name: Update APT Repo and Cache
      become: yes
      ansible.builtin.apt: update_cache=yes

    - name: Update all Packages
      become: yes
      ansible.builtin.apt: 
        name: "*"
        state: latest 

    # - name: Reboot the server
    #   become: yes
    #   reboot:
    #     msg: "Reboot initiated by Ansible due to kernel updates"
    #     connect_timeout: 5
    #     reboot_timeout: 300
    #     pre_reboot_delay: 0
    #     post_reboot_delay: 30
    #     test_command: uptime

    - name: Install NginX
      become: yes 
      ansible.builtin.package:
        name: 
          - nginx-common
          - nginx
        state: latest


    - name: copy deployment private key
      become: yes
      copy:
        content: "{{private_key_content}}"
        dest: "/etc/nginx/ssl/servermanagementpanel.de.key.new"
        owner: root
        group: root
        mode: 0600







  # - name: copy deployment private key
  #   copy:
  #     content: "{{private_key_content}}"
  #     dest: "/home/marvin/.ssh/id_rsa"
  #     owner: marvin
  #     group: marvin
  #     mode: 0600
  #   no_log: true
